# Generated by Django 5.2.15 on 2026-08-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, help_text='Числовой id пользователя в Telegram (из initData).', unique=True)),
                ('username', models.CharField(blank=True, default='', help_text='Telegram @username без @; может быть пустым.', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('language_code', models.CharField(blank=True, default='ru', help_text='Код языка клиента Telegram (ru, en, …).', max_length=16)),
                ('is_premium', models.BooleanField(default=False, help_text='Telegram Premium у пользователя (из initDataUnsafe).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.ForeignKey(blank=True, help_text='Кто привёл пользователя по реферальной ссылке (фаза 3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_persona_id', models.PositiveBigIntegerField(blank=True, help_text='pk персонажа (content.Persona), когда каталог появится.', null=True)),
                ('locale', models.CharField(default='ru', help_text='Локаль UI/генерации (пока ru).', max_length=16)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Разрешены ли push/уведомления от бота.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Владелец настроек.', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
