# Generated by Django 5.2.15 on 2026-08-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_content_models_and_favorite_persona'),
        ('users', '0001_initial_telegram_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='favorite_persona_id',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='favorite_persona',
            field=models.ForeignKey(blank=True, help_text='Любимый персонаж пользователя (каталог content).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by_settings', to='content.persona'),
        ),
    ]
