# Generated by Django 5.2.15 on 2026-08-09 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_telegram_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Стабильный ключ API: greeting, horoscope, …', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Отображаемое имя (Поздравление).', max_length=128)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('phase', models.PositiveSmallIntegerField(default=1, help_text='Фаза roadmap, с которой режим доступен пользователю.')),
                ('is_active', models.BooleanField(default=True, help_text='Выкл. — скрыть из каталога без удаления истории.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньше значение — выше в списке.')),
            ],
            options={
                'verbose_name': 'Режим контента',
                'verbose_name_plural': 'Режимы контента',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('season_start', models.DateField(blank=True, help_text='Начало сезона (nullable — повод без сезона, напр. ДР).', null=True)),
                ('season_end', models.DateField(blank=True, help_text='Конец сезона; пусто = не сезонное событие.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тип повода',
                'verbose_name_plural': 'Типы поводов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, default='', help_text='Короткий титул: «пророчица с лавочки».', max_length=255)),
                ('category', models.CharField(choices=[('mystic', 'Мистика'), ('humor', 'Юмор'), ('sages', 'Мудрецы'), ('history', 'История')], db_index=True, default='humor', max_length=32)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('gradient', models.CharField(blank=True, default='', help_text='CSS-градиент карточки, напр. from-amber-500 to-rose-600.', max_length=128)),
                ('voice_tone', models.CharField(blank=True, default='', help_text='Тон речи для промпта: «ворчливо, по-доброму».', max_length=255)),
                ('signature', models.CharField(blank=True, default='', help_text='Фирменная стартовая фраза персонажа.', max_length=255)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Базовый system prompt (до Jinja2-шаблонов).')),
                ('is_premium', models.BooleanField(default=False, help_text='True — только для Premium (фаза 3).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Ввод мастера: имя, дата, повод, extra, …')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('completed', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='', help_text='Техническая ошибка при failed (пользователю не показываем traceback).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='content.contentmode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='users.telegramuser')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='content.persona')),
            ],
            options={
                'verbose_name': 'Генерация',
                'verbose_name_plural': 'Генерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body_text', models.TextField(help_text='Основной текст для экрана результата.')),
                ('share_text', models.TextField(blank=True, default='', help_text='Готовый текст для шеринга в Telegram (с подписью).')),
                ('source', models.CharField(choices=[('llm', 'LLM'), ('template', 'Шаблон (fallback)')], default='template', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='content.generation')),
            ],
            options={
                'verbose_name': 'Результат генерации',
                'verbose_name_plural': 'Результаты генераций',
            },
        ),
    ]
