# Generated by Django 5.2.15 on 2026-08-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_content_models_and_favorite_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null для free; для premium — дата окончания.', null=True)),
                ('telegram_payment_id', models.CharField(blank=True, default='', help_text='Id платежа Telegram Stars (фаза 3).', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Владелец подписки.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Локальная дата учёта.')),
                ('generations_count', models.PositiveIntegerField(default=0, help_text='Сколько текстовых генераций уже сделано сегодня.')),
                ('media_count', models.PositiveIntegerField(default=0, help_text='Сколько медиа-запросов (фаза 2).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Дневная квота',
                'verbose_name_plural': 'Дневные квоты',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='billing_usagequota_user_date_uniq')],
            },
        ),
    ]
